name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "*.sh"

env:
  REGISTRY: ghcr.io
  ACTOR: ${{ github.actor }}
  ORIGIN: bashonly/manylinux2014-build-image

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_manylinux:
    name: ${{ matrix.policy }}_${{ matrix.platform }}_builds
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - policy: manylinux2014
          platform: x86_64
          runner: ubuntu-24.04
        - policy: manylinux2014
          platform: aarch64
          runner: ubuntu-24.04-arm
        - policy: manylinux_2_31
          platform: armv7l
          runner: ubuntu-24.04-arm
        - policy: musllinux_1_2
          platform: x86_64
          runner: ubuntu-24.04
        - policy: musllinux_1_2
          platform: aarch64
          runner: ubuntu-24.04-arm

    env:
      POLICY: ${{ matrix.policy }}
      PLATFORM: ${{ matrix.platform }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == env.ORIGIN
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./build.sh

      - name: Deploy
        run: ./deploy.sh
